name: laams_push
description: A declarative URI-based router for advanced navigation in Flutter,
  tailored for deep linking, user auth-based navigation, custom transition
  animations, ease of use, and many more.
version: 1.0.1
homepage: https://laams.io
repository: https://github.com/laams/laams_push
issue_tracker: https://github.com/laams/laams_push/issues

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter: null
